# Generated by Django 3.1.3 on 2020-11-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.CharField(choices=[('News', 'Новости'), ('Serials', 'Сериалы'), ('Films', 'Фильмы'), ('Cartoons', 'Мультфильмы'), ('TV_show', 'Телешоу')], max_length=128, verbose_name='Тип программы')),
                ('name_program', models.CharField(max_length=256, verbose_name='Имя телепрограммы')),
                ('time_program', models.TimeField()),
                ('day_program', models.CharField(choices=[('Monday', 'Понедельник'), ('Tuesday', 'Вторник'), ('Wednesday', 'Среда'), ('Thursday', 'Четверг'), ('Friday', 'Пятница'), ('Saturday', 'Суббота'), ('Sunday', 'Воскресенье')], max_length=256, verbose_name='Дни недели')),
            ],
            options={
                'verbose_name': 'Телеканал',
            },
        ),
    ]
