# Generated by Django 3.1.3 on 2020-11-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_auto_20201116_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='program_type',
            field=models.CharField(choices=[('Новини', 'Новини'), ('Серіали', 'Серіали'), ('Фільми', 'Фільми'), ('Мультфільми', 'Мультфільмы'), ('Телешоу', 'Телешоу'), ('Нічная музика', 'Нічная музика')], max_length=128, verbose_name='Тип программы'),
        ),
    ]
